name: injectable_generator
description: Injectable is a convenient code generator for get_it. Inspired by Angular DI, Guice DI and inject.dart.
version: 2.6.2
homepage: https://github.com/Milad-Akarie/injectable
publish_to: "none"

environment:
  sdk: ">=3.0.0<4.0.0"

dependencies:
  build: ^2.4.2
  source_gen: ^2.0.0
  path: ^1.9.1
  glob: ^2.1.3
  analyzer: ^7.3.0
  code_builder: ^4.10.1
  dart_style: ^3.0.1
  injectable:
    path: ../injectable
  collection: ^1.19.1
  recase: ^4.1.0
  meta: ^1.16.0
dev_dependencies:
  build_runner: ^2.4.15
  build_test: ^2.2.3
  test: ^1.25.15
  lints: ^5.1.1
